// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB1GgqPc0j8S0GeRx99AXdotQddpWnhCC4',
//     appId: '1:675554995946:web:4ac2be7dfcb32e3727f193',
//     messagingSenderId: '675554995946',
//     projectId: 'irescue-hacka',
//     authDomain: 'irescue-hacka.firebaseapp.com',
//     databaseURL: 'https://irescue-hacka-default-rtdb.firebaseio.com',
//     storageBucket: 'irescue-hacka.firebasestorage.app',
//     measurementId: 'G-L34S93LEQ2',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyClh4OMTF95YblRtU85N4c8gfNeZVs6rtw',
//     appId: '1:675554995946:android:323b1469b6a2dcb127f193',
//     messagingSenderId: '675554995946',
//     projectId: 'irescue-hacka',
//     databaseURL: 'https://irescue-hacka-default-rtdb.firebaseio.com',
//     storageBucket: 'irescue-hacka.firebasestorage.app',
//   );
// }
